name: GeneratePage

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  vuepress:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create VuePress Page
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PUBLISH_TO_BRANCH: live # live is our publishing branch
        BASE_URL: https://codingluke.github.io/bbzbl-module-page-template/ # TODO: get repo name automaticlly!
      uses: codingluke/bbzbl-module-page-action@main
